version: "3.9"

services:
  app:
    container_name: hello-wops
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb_service
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: redis_service
    image: "redis:latest"

  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    ports:
      - "27017:27017"