version: "3.9"

services:
  redis:
    container_name: redis_service
    image: "redis:latest"
    hostname: redis_database
    networks:
      - app_network

  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    hostname: mongodb_database
    ports:
      - "27017:27017"
    networks:
      - app_network

  app:
    container_name: hello-wops
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb_database
      - MONGO_PORT=27017
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
    networks:
      - app_network
    volumes:
      - ~/Desktop/DevOPs/:/logs

networks:
  app_network:
    driver: bridge